services:
  db:
    container_name: payment_service_pg
    image: postgres:15
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -p ${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${DB_PORT} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  app:
    container_name: payment_service_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  