// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: payment-service.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Общий enum для статусов ответов
type ResponseStatus int32

const (
	ResponseStatus_UNKNOWN               ResponseStatus = 0
	ResponseStatus_SUCCESS               ResponseStatus = 1
	ResponseStatus_INSUFFICIENT_QUANTITY ResponseStatus = 2
	ResponseStatus_INTERNAL_ERROR        ResponseStatus = 3
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "INSUFFICIENT_QUANTITY",
		3: "INTERNAL_ERROR",
	}
	ResponseStatus_value = map[string]int32{
		"UNKNOWN":               0,
		"SUCCESS":               1,
		"INSUFFICIENT_QUANTITY": 2,
		"INTERNAL_ERROR":        3,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_service_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_payment_service_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{0}
}

// Сообщение для запроса резервирования денег
type ReservePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePaymentRequest) Reset() {
	*x = ReservePaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePaymentRequest) ProtoMessage() {}

func (x *ReservePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePaymentRequest.ProtoReflect.Descriptor instead.
func (*ReservePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReservePaymentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReservePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Сообщение для ответа на резервирование денег
type ReservePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=api.v1.paymentservice.ResponseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePaymentResponse) Reset() {
	*x = ReservePaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePaymentResponse) ProtoMessage() {}

func (x *ReservePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePaymentResponse.ProtoReflect.Descriptor instead.
func (*ReservePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReservePaymentResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_UNKNOWN
}

// Сообщение для запроса компенсации денег
type CompensatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompensatePaymentRequest) Reset() {
	*x = CompensatePaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensatePaymentRequest) ProtoMessage() {}

func (x *CompensatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CompensatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{2}
}

func (x *CompensatePaymentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CompensatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Сообщение для ответа на компенсацию денег
type CompensatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=api.v1.paymentservice.ResponseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompensatePaymentResponse) Reset() {
	*x = CompensatePaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensatePaymentResponse) ProtoMessage() {}

func (x *CompensatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CompensatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{3}
}

func (x *CompensatePaymentResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_UNKNOWN
}

var File_payment_service_proto protoreflect.FileDescriptor

const file_payment_service_proto_rawDesc = "" +
	"\n" +
	"\x15payment-service.proto\x12\x15api.v1.paymentservice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n" +
	"\x15ReservePaymentRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x1f\n" +
	"\x06amount\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06amount\"W\n" +
	"\x16ReservePaymentResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.api.v1.paymentservice.ResponseStatusR\x06status\"]\n" +
	"\x18CompensatePaymentRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x1f\n" +
	"\x06amount\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06amount\"Z\n" +
	"\x19CompensatePaymentResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.api.v1.paymentservice.ResponseStatusR\x06status*Y\n" +
	"\x0eResponseStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x19\n" +
	"\x15INSUFFICIENT_QUANTITY\x10\x02\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x032\xc4\x02\n" +
	"\x0ePaymentService\x12\x91\x01\n" +
	"\x0eReservePayment\x12,.api.v1.paymentservice.ReservePaymentRequest\x1a-.api.v1.paymentservice.ReservePaymentResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/payment/reserve\x12\x9d\x01\n" +
	"\x11CompensatePayment\x12/.api.v1.paymentservice.CompensatePaymentRequest\x1a0.api.v1.paymentservice.CompensatePaymentResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/payment/compensateB\x81\x01\x92An\x12H\n" +
	"\x0fPayment service\x12.Service for managing payments and reservations2\x051.0.02\x10application/json:\x10application/jsonZ\x0epkg/api/v1;apib\x06proto3"

var (
	file_payment_service_proto_rawDescOnce sync.Once
	file_payment_service_proto_rawDescData []byte
)

func file_payment_service_proto_rawDescGZIP() []byte {
	file_payment_service_proto_rawDescOnce.Do(func() {
		file_payment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)))
	})
	return file_payment_service_proto_rawDescData
}

var file_payment_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_service_proto_goTypes = []any{
	(ResponseStatus)(0),               // 0: api.v1.paymentservice.ResponseStatus
	(*ReservePaymentRequest)(nil),     // 1: api.v1.paymentservice.ReservePaymentRequest
	(*ReservePaymentResponse)(nil),    // 2: api.v1.paymentservice.ReservePaymentResponse
	(*CompensatePaymentRequest)(nil),  // 3: api.v1.paymentservice.CompensatePaymentRequest
	(*CompensatePaymentResponse)(nil), // 4: api.v1.paymentservice.CompensatePaymentResponse
}
var file_payment_service_proto_depIdxs = []int32{
	0, // 0: api.v1.paymentservice.ReservePaymentResponse.status:type_name -> api.v1.paymentservice.ResponseStatus
	0, // 1: api.v1.paymentservice.CompensatePaymentResponse.status:type_name -> api.v1.paymentservice.ResponseStatus
	1, // 2: api.v1.paymentservice.PaymentService.ReservePayment:input_type -> api.v1.paymentservice.ReservePaymentRequest
	3, // 3: api.v1.paymentservice.PaymentService.CompensatePayment:input_type -> api.v1.paymentservice.CompensatePaymentRequest
	2, // 4: api.v1.paymentservice.PaymentService.ReservePayment:output_type -> api.v1.paymentservice.ReservePaymentResponse
	4, // 5: api.v1.paymentservice.PaymentService.CompensatePayment:output_type -> api.v1.paymentservice.CompensatePaymentResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payment_service_proto_init() }
func file_payment_service_proto_init() {
	if File_payment_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_proto_goTypes,
		DependencyIndexes: file_payment_service_proto_depIdxs,
		EnumInfos:         file_payment_service_proto_enumTypes,
		MessageInfos:      file_payment_service_proto_msgTypes,
	}.Build()
	File_payment_service_proto = out.File
	file_payment_service_proto_goTypes = nil
	file_payment_service_proto_depIdxs = nil
}
