// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: payment-service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_ReserveUserBalance_FullMethodName    = "/api.v1.paymentservice.PaymentService/ReserveUserBalance"
	PaymentService_CompensateUserBalance_FullMethodName = "/api.v1.paymentservice.PaymentService/CompensateUserBalance"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис управления балансом пользователей
type PaymentServiceClient interface {
	// Резервирование баланса пользователя
	ReserveUserBalance(ctx context.Context, in *ReserveUserBalanceRequest, opts ...grpc.CallOption) (*ReserveUserBalanceResponse, error)
	// Компенсация баланса пользователя (отмена резервирования)
	CompensateUserBalance(ctx context.Context, in *CompensateUserBalanceRequest, opts ...grpc.CallOption) (*CompensateUserBalanceResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) ReserveUserBalance(ctx context.Context, in *ReserveUserBalanceRequest, opts ...grpc.CallOption) (*ReserveUserBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveUserBalanceResponse)
	err := c.cc.Invoke(ctx, PaymentService_ReserveUserBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CompensateUserBalance(ctx context.Context, in *CompensateUserBalanceRequest, opts ...grpc.CallOption) (*CompensateUserBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompensateUserBalanceResponse)
	err := c.cc.Invoke(ctx, PaymentService_CompensateUserBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
//
// Сервис управления балансом пользователей
type PaymentServiceServer interface {
	// Резервирование баланса пользователя
	ReserveUserBalance(context.Context, *ReserveUserBalanceRequest) (*ReserveUserBalanceResponse, error)
	// Компенсация баланса пользователя (отмена резервирования)
	CompensateUserBalance(context.Context, *CompensateUserBalanceRequest) (*CompensateUserBalanceResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) ReserveUserBalance(context.Context, *ReserveUserBalanceRequest) (*ReserveUserBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveUserBalance not implemented")
}
func (UnimplementedPaymentServiceServer) CompensateUserBalance(context.Context, *CompensateUserBalanceRequest) (*CompensateUserBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompensateUserBalance not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_ReserveUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ReserveUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ReserveUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ReserveUserBalance(ctx, req.(*ReserveUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CompensateUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompensateUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CompensateUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CompensateUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CompensateUserBalance(ctx, req.(*CompensateUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.paymentservice.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveUserBalance",
			Handler:    _PaymentService_ReserveUserBalance_Handler,
		},
		{
			MethodName: "CompensateUserBalance",
			Handler:    _PaymentService_CompensateUserBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment-service.proto",
}
